# Generated by Django 3.0.6 on 2020-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createpoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnum', models.CharField(max_length=3, null=True)),
                ('que', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=100, null=True)),
                ('opt2', models.CharField(max_length=100, null=True)),
                ('opt3', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
