# Generated by Django 3.0.6 on 2020-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='vo1',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='createpoll',
            name='vo2',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='createpoll',
            name='vo3',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
