# Generated by Django 3.0.6 on 2020-07-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0002_auto_20200718_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpoll',
            name='qnum',
        ),
    ]
